### ISSUE TITLE
Docs: fix the property type column

### ISSUE THREAD

**Issue by nokome** [stencila/schema#104]
The generated property table does not properly generate the type of non-primitive properties. For example, `CreativeWork` has these two properties, using `allOf` and `anyOf`:

```yaml
  isPartOf:
    '@id': schema:isPartOf
    description: |
      An item or other CreativeWork that this CreativeWork is a part of.
    allOf:
      - $ref: CreativeWork
  licenses:
    '@id': schema:license
    description: |
      License documents that applies to this content, typically indicated by URL.
    type: array
    items:
      anyOf:
        - type: string
          format: uri
        - $ref: CreativeWork
```

These get rendered as:

```md
| isPartOf              | ``       | An item or other CreativeWork that this CreativeWork is a part of.                                                       | [CreativeWork](./CreativeWork.html) |
| licenses              | `array`  | License documents that applies to this content, typically indicated by URL.                                              | [CreativeWork](./CreativeWork.html) |
```

but the expected output is something like:

```md
| isPartOf              | [CreativeWork](./CreativeWork.html)                       | An item or other CreativeWork that this CreativeWork is a part of.                                                       | [CreativeWork](./CreativeWork.html) |
| licenses              | Array<string|[CreativeWork](./CreativeWork.html)> | License documents that applies to this content, typically indicated by URL.                                              | [CreativeWork](./CreativeWork.html) |
```

See `bindings.ts` for how we determine the type of a property for Typescript, Python etc e.g.

https://github.com/stencila/schema/blob/34ae0bf3c9c4c8912e3e95754242898c4d216866/src/typescript.ts#L151-L163
