### ISSUE TITLE
Question re. Article/CreativeWork schema

### ISSUE THREAD

**Issue by alex-ketch** [stencila/schema#137]
While pairing on styling citation references with @jwijay, we came across a desired use case for recording both the `title` of a cited article, as well as the `name` of the journal/publication that distributed it.

A draft of the HTML we were manipulating can be seen below.

```html
<li itemscope itemtype="https://schema.org/CreativeWork">
  <a
    href="https://doi.org/10.1016/j.cell.2010.07.042"
    itemprop="title"
  >
    Cell flow reorients the axis of planar polarity in the wing epithelium of Drosophila
  </a>

  <ol itemprop="authors">
    <!-- Author list here -->
  </ol>

  <time itemprop="datePublished" datetime="2010-01-01">(2010)</time>

  <!-- ? How to represent the information below ? -->
  <ul
    itemscope
    itemtype="https://stencila.github.io/schema/PublicationIssue"
  >
    <em itemprop="title">Cell</em>
    <strong itemprop="issueNumber">142</strong
    ><time itemprop="datePublished" datetime="2010">(2010)</time
    ><span itemprop="pagination">773–786</span>
  </ul>
</li>
```

I see a few way of handling this, but would like some feedback.

1. Change the top level entry to be a `PublicationIssue` with the `Article` listed in the `parts`.
    - This allows to record the necessary information, but buries the primary content in the schema, making our desire of universally styled citations a bit harder.

2. Add a `publishedIn` field to `CreativeWork`, containing a list of other `CreativeWorks`
    - This maintains a more intuitive hierarchy of information when dealing with citation references, and potentially allows referring to multiple published instances if needed.

3. Use `title` from `CreativeWork` for article title, and `name` inherited from `Thing` for publisher 👎 
    - The name field adds confusion when schemas have other similar properties such as title, and the distinction between the two is unclear. Is deprecating `name`, or using `title` as an `alias` of `name`,  feasible or even desirable @nokome?

**Comment by nokome** [comment]
Option 2, but using the existing `isPartOf` property, seems to be the standard approach, and is the approach that we have been using in Encoda e.g.

```bash
./encoda convert https://doi.org/10.7554/eLife.48932 --from doi - --to json
```

```json
{
  "authors": [
    {
      "familyNames": [
        "Sitek"
      ],
      "givenNames": [
        "Kevin R"
      ],
      "type": "Person"
    },
    ...
  ],
  "title": "Mapping the human subcortical auditory system using histology, postmortem MRI and in vivo MRI at 7T",
  "datePublished": "2019,8,1",
  "isPartOf": {
    "volumeNumber": "8",
    "isPartOf": {
      "title": "eLife",
      "type": "Periodical"
    },
    "type": "PublicationVolume"
  },
  "type": "Article"
}
```

This example does not have a `PublicationIssue`, but if that is present, then that would add another level of nesting - see the example at the bottom of https://schema.stenci.la/PublicationIssue

**Comment by nokome** [comment]
Just came across an article with `PublicationIssue` so though I'd share it here.

```bash
./encoda convert "10.1371/journal.pone.0216012" temp.yaml
```

```yaml
authors:
  - familyNames:
      - Salerni
    givenNames:
      - Fabrizia
    type: Person
  - familyNames:
      - Repetto
    givenNames:
      - Rodolfo
    type: Person
  - familyNames:
      - Harris
    givenNames:
      - Alon
    type: Person
  - familyNames:
      - Pinsky
    givenNames:
      - Peter
    type: Person
  - familyNames:
      - Prud’homme
    givenNames:
      - Christophe
    type: Person
  - familyNames:
      - Szopos
    givenNames:
      - Marcela
    type: Person
  - familyNames:
      - Guidoboni
    givenNames:
      - Giovanna
    type: Person
title: >-
  Biofluid modeling of the coupled eye-brain system and insights into simulated
  microgravity conditions
datePublished: '2019,8,14'
isPartOf:
  issueNumber: '8'
  isPartOf:
    volumeNumber: '14'
    isPartOf:
      title: PLOS ONE
      type: Periodical
    type: PublicationVolume
  type: PublicationIssue
type: Article
```
