### ISSUE TITLE
Add a Math type

### ISSUE THREAD

**Issue by nokome** [stencila/schema#154]
We are missing a `Math` node type/s. I suggest the following, which mirrors the `Code`, `CodeFragment`, `CodeBlock` heirarchy:

```yaml
title: Math
'@id': stencila:Math
extends: Entity
role: secondary
status: unstable
category: prose
description: A mathematical equation.
properties:
  mathLanguage:
    '@id': schema:mathLanguage
    description: The language used for the equation e.g tex, mathml, asciimath.
    type: string
    default: 'tex'
  text:
    '@id': schema:text
    description: The text of the equation in the language.
    type: string
required:
  - text

title: MathFragment
'@id': stencila:MathFragment
extends: Math
role: secondary
status: unstable
category: prose
description: A block of math, e.g. a variable name, to be displayed as inline content.
properties: {}

title: MathBlock
'@id': stencila:MathBlock
extends: Math
role: secondary
status: unstable
category: prose
description: A block of math, e.g an equation, to be displayed as block content.
properties: {}
```

For reference, Pandoc's `Math` type has display type but only allows for Tex as a language:

https://github.com/stencila/encoda/blob/6f829776bd9104e39da3b151899174b38d750d1a/src/codecs/pandoc/types.ts#L382-L392

In Encoda, there is already some handling of Math nodes in JATS:

https://github.com/stencila/encoda/blob/6f829776bd9104e39da3b151899174b38d750d1a/src/codecs/jats/index.ts#L1369-L1398

and in HTML:

https://github.com/stencila/encoda/blob/1270e7238831de92fc108e3d2a2d95c8052033f3/src/codecs/html/index.ts#L1589-L1594
