### ISSUE TITLE
Add label property to MathBlock

### ISSUE THREAD

**Issue by nokome** [stencila/schema#246]
Currently the `label` property is on `Figure`, `Table` and `CodeChunk` and is used to store strings like "Figure 1", "Table 2". Similarly, we need to add label to `MathBlock` e.g.

```yaml
 label:
    '@id': stencila:label
    description: A short label for the math block.
    type: string
```

Necessary for https://github.com/stencila/encoda/issues/837
